cptbox: remove legacy PTBOX_HANDLER_STDOUTERR
DMOJ/judge-server pull request #1006
Opened 2022-02-28 16:27 UTC by Riolku

This is from a time when we trapped `write`, and checked the arguments of it, neither of which is true now.

2022-02-28 16:27 UTC, dmoj-build commented
Can one of the admins verify this patch?

2022-02-28 16:45 UTC, kiritofeng commented
ok to test

2022-02-28 23:46 UTC, quantum5 submitted a review, later dismissed

2022-02-28 23:48 UTC, quantum5 requested changes
Lots more references... https://github.com/DMOJ/judge-server/blob/bc88654d40a39ccc5dc24dad5127150bbc792d7b/dmoj/cptbox/handlers.py#L8 and https://github.com/DMOJ/judge-server/blob/bc88654d40a39ccc5dc24dad5127150bbc792d7b/dmoj/cptbox/handlers.py#L8 needs to be removed.

2022-03-01 00:26 UTC, Riolku commented
You say lots more, but are these the only two?

2022-03-01 00:30 UTC, quantum5 approved these changes
LGTM assuming tests pass

2022-03-01 05:28 UTC, merged