Report interactor compile error as internal error
DMOJ/judge-server pull request #1115
Opened 2023-02-27 22:33 UTC by Balint-R

Before this change, the interactor failing to compile was reported in the same way as the user's submission failing to compile.

2023-02-27 22:36 UTC, kiritofeng requested changes
Otherwise LGTM

2023-02-27 22:36 UTC, kiritofeng commented on dmoj/graders/bridged.py
> +            # Rethrow as IE to differentiate from the user's submission CEing
```suggestion
            # Rethrow as IE to differentiate from the user's submission failing to compile.
```

2023-02-27 22:36 UTC, kiritofeng commented on dmoj/graders/bridged.py
> +from dmoj.error import CompileError
Can we merge this with the line below (so `from dmoj.error import CompileError, InternalError`

2023-02-28 01:03 UTC, kiritofeng approved these changes
LGTM, thanks!

2023-02-28 01:04 UTC, kiritofeng commented on dmoj/graders/bridged.py
> +            raise InternalError("Interactor failed compiling") from compilation_error
Can you change these to single quotes so flake8 stops being sad

2023-02-28 21:13 UTC, Xyene commented on dmoj/graders/bridged.py
> +            raise InternalError('Interactor failed compiling') from compilation_error
Nit for consistency with most other errors
```suggestion
            raise InternalError('interactor failed compiling') from compilation_error
```

2023-03-02 11:58 UTC, Xyene approved these changes
LGTM, thanks!

2023-03-02 12:10 UTC, merged