Allow for checkers to call `int()`
DMOJ/judge-server pull request #843
Opened 2021-03-29 15:12 UTC by kiritofeng

The current behaviour requires an argument to be passed to `int(...)`, however, this breaks `defaultdict(int)`.

2021-03-29 15:20 UTC, Ninjaclasher approved these changes

2021-03-29 16:00 UTC, WallE256 approved these changes

2021-03-29 16:09 UTC, Xyene approved these changes

2021-03-29 16:10 UTC, Xyene commented
LGTM, but could you also add a test for this in https://github.com/DMOJ/judge-server/blob/master/dmoj/tests/test_int_patch.py?

2021-03-30 03:23 UTC, quantum5 requested changes
Looks good, but will not merge unless there is a test.

2021-04-02 04:02 UTC, quantum5 approved these changes

2021-04-02 04:02 UTC, merged