Detect WSL 1 and apply waitpid hack to it only
DMOJ/judge-server pull request #874
Opened 2021-09-01 21:01 UTC by quantum5

It appears that WSL 1 uses capitalized "Microsoft" while WSL2 doesn't,
and this is used to distinguish between the WSL versions.

2021-09-01 21:05 UTC, Xyene requested changes
Please rename the define to be more explicit as well.

2021-09-01 21:07 UTC, quantum5 commented
> Please rename the define to be more explicit as well.

Done.

2021-09-01 21:24 UTC, Xyene approved these changes
LGTM

2021-09-02 03:00 UTC, hieplpvip commented
Confirmed working on WSL2 Ubuntu 20.04

2021-09-02 03:11 UTC, merged